"""add cdsl transaction events

Revision ID: 1c934d88029e
Revises: fd7b3cf0bdc5
Create Date: 2026-08-22 08:16:49.755886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1c934d88029e'
down_revision: Union[str, Sequence[str], None] = 'fd7b3cf0bdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cdsl_transaction_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('security_name', sa.String(length=255), nullable=False),
        sa.Column('isin', sa.String(length=20), nullable=False),
        sa.Column(
            'quantity',
            sa.Numeric(precision=20, scale=8),
            nullable=False,
        ),
        sa.Column(
            'direction',
            sa.Enum(
                'CREDIT',
                'DEBIT',
                name='cdsl_transaction_direction',
            ),
            nullable=False,
        ),
        sa.Column(
            'transaction_datetime',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column('source', sa.String(length=50), nullable=False),
        sa.Column(
            'source_reference',
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column('processed', sa.Boolean(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'user_id',
            'source',
            'source_reference',
            name='uq_cdsl_event_source_reference',
        ),
    )

    op.create_index(
        op.f('ix_cdsl_transaction_events_isin'),
        'cdsl_transaction_events',
        ['isin'],
        unique=False,
    )

    op.create_index(
        op.f('ix_cdsl_transaction_events_transaction_datetime'),
        'cdsl_transaction_events',
        ['transaction_datetime'],
        unique=False,
    )

    op.create_index(
        op.f('ix_cdsl_transaction_events_user_id'),
        'cdsl_transaction_events',
        ['user_id'],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_cdsl_transaction_events_user_id'),
        table_name='cdsl_transaction_events',
    )

    op.drop_index(
        op.f('ix_cdsl_transaction_events_transaction_datetime'),
        table_name='cdsl_transaction_events',
    )

    op.drop_index(
        op.f('ix_cdsl_transaction_events_isin'),
        table_name='cdsl_transaction_events',
    )

    op.drop_table('cdsl_transaction_events')