"""add asset table

Revision ID: 21a3166c6422
Revises: 826327e7fea2
Create Date: 2026-08-07 06:35:08.907660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a3166c6422'
down_revision: Union[str, Sequence[str], None] = '826327e7fea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('STOCK', 'MUTUAL_FUND', 'ETF', 'GOLD', 'FIXED_DEPOSIT', name='assettype'), nullable=False),
    sa.Column('exchange', sa.Enum('NSE', 'BSE', 'AMFI', 'MCX', name='exchange'), nullable=False),
    sa.Column('currency', sa.Enum('INR', 'USD', name='currency'), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_exchange_symbol'),
    sa.UniqueConstraint('isin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    # ### end Alembic commands ###
